ia/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('consejos/', views.consejos, name="consejos"),
]

venta/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('venta/', views.venta, name="venta"),
    path('nueva/', views.nueva_venta, name='nueva_venta'),
    path('detalle/<int:venta_id>/', views.detalle_venta, name='detalle_venta'),
    path('eliminar/<int:venta_id>/', views.eliminar_venta, name='eliminar_venta'),
    path('eliminar-detalle/<int:detalle_id>/', views.eliminar_detalle, name='eliminar_detalle'),
    path('descargar-excel/<int:venta_id>/', views.descargar_venta_excel, name='descargar_venta_excel'),
    path('descargar-ventas-excel/', views.descargar_ventas_excel, name='descargar_ventas_excel'),
]

venta/models.py
from django.db import models
from django.conf import settings
from agenda.models import Cliente
from stock.models import Producto
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError

class Venta(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fecha = models.DateTimeField(verbose_name="Fecha de la venta")
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Cliente asociado")
    código = models.IntegerField(default=0, null=False, blank=False)
    total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Total de la venta", default=0)
    
    class Meta:
        indexes = [
            models.Index(fields=['user']),  # Índice para mejorar consultas por usuario
            models.Index(fields=['código']),  # Índice para búsquedas por nombre
            models.Index(fields=['cliente']),
            models.Index(fields=['fecha']),
        ]

    def __str__(self):
        return f"Venta #{self.id} - {self.fecha.strftime('%Y-%m-%d %H:%M')}"

    def delete(self, *args, **kwargs):
        for detalle in self.detalles.all():
            # Devolver el stock del producto solo si existe
            if detalle.producto:
                detalle.producto.stock += detalle.cantidad
                detalle.producto.save()
        super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        # Calcular el total solo si la venta ya existe
        if self.pk:
            self.total = sum(detalle.subtotal for detalle in self.detalles.all())
        super().save(*args, **kwargs)      
    

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, related_name="detalles")
    producto = models.ForeignKey(Producto, on_delete=models.SET_NULL, null=True, blank=True)
    nombre_producto = models.CharField(max_length=40, verbose_name="Nombre del producto", null=True)
    cantidad = models.PositiveIntegerField(verbose_name="Cantidad vendida", default=1)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio unitario", default=0)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Subtotal", default=0)

    def __str__(self):
        if self.producto:
            return f"{self.producto.nombre} - {self.cantidad} unidades"
        return f"{self.nombre_producto} - {self.cantidad} unidades"

    def save(self, *args, **kwargs):
        # Actualizar el stock del producto y calcular subtotal
        if self.pk:
            detalle_anterior = DetalleVenta.objects.get(pk=self.pk)
            diferencia_cantidad = self.cantidad - detalle_anterior.cantidad
            if self.producto:
                if diferencia_cantidad > 0:
                    self.producto.stock -= diferencia_cantidad
                elif diferencia_cantidad < 0:
                    self.producto.stock -= diferencia_cantidad
        else:
            if self.producto:
                self.producto.stock -= self.cantidad
                # Guardar el nombre del producto al momento de la venta
                self.nombre_producto = self.producto.nombre

        if self.producto:
            self.precio_unitario = self.producto.precio_de_venta
            self.subtotal = self.cantidad * self.precio_unitario

        if self.producto:
            self.producto.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Devolver el stock al eliminar el detalle
        if self.producto:
            self.producto.stock += self.cantidad
            self.producto.save()
    
        # Actualizar el total de la venta
        venta = self.venta
        super().delete(*args, **kwargs)  # Primero elimina el detalle
        venta.total = sum(detalle.subtotal for detalle in venta.detalles.all())
        venta.save()  # Guarda la venta con el nuevo total

#------------------------------------------------------------------------------------

@receiver(post_save, sender=DetalleVenta)
def actualizar_total_venta(sender, instance, **kwargs):
    venta = instance.venta
    venta.total = sum(detalle.subtotal for detalle in venta.detalles.all())
    venta.save()

venta/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Venta, DetalleVenta, Cliente
from stock.models import Producto
from .forms import VentaForm, DetalleVentaForm
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.http import HttpResponse
import openpyxl
from openpyxl.styles import Font, Alignment, NamedStyle, PatternFill, Border, Side
from datetime import datetime
from django.views.decorators.cache import never_cache

# Create your views here.
@login_required
@never_cache
def venta(request):
    search_date_specific = request.GET.get('search_date_specific', '')
    search_date_start = request.GET.get('search_date_start', '')
    search_date_end = request.GET.get('search_date_end', '')
    search_code = request.GET.get('search_code', '')
    
    ventas_list = Venta.objects.filter(user=request.user)
    
    # Aplicar filtros de fecha
    if search_date_specific:
        ventas_list = ventas_list.filter(fecha__date=search_date_specific)
    else:
        if search_date_start:
            ventas_list = ventas_list.filter(fecha__date__gte=search_date_start)
        if search_date_end:
            ventas_list = ventas_list.filter(fecha__date__lte=search_date_end)
        
    # Aplicar filtros de código o cliente independientemente de las fechas
    if search_code:
        # Si la búsqueda contiene la palabra "minorista", incluir ventas sin cliente
        if 'desco' in search_code.lower():
            ventas_list = ventas_list.filter(
                Q(código__icontains=search_code) |
                Q(cliente__nombre__icontains=search_code) |
                Q(cliente__isnull=True)
            )
        else:
            ventas_list = ventas_list.filter(
                Q(código__icontains=search_code) |
                Q(cliente__nombre__icontains=search_code)
            )
        
    ventas_list = ventas_list.select_related('user', 'cliente').order_by('-fecha')

    page = request.GET.get('page', 1)
    paginator = Paginator(ventas_list, 20)
    try:
        ventas = paginator.page(page)
    except PageNotAnInteger:
        ventas = paginator.page(1)
    except EmptyPage:
        ventas = paginator.page(paginator.num_pages)

    context = {
        'ventas': ventas,
        'total': ventas_list.count(),
        'search_date_specific': search_date_specific,
        'search_date_start': search_date_start,
        'search_date_end': search_date_end,
        'search_code': search_code
    }
    return render(request, 'venta/venta.html', context)

@login_required
@never_cache
def nueva_venta(request):
    if request.method == 'POST':
        form = VentaForm(request.POST, user=request.user)
        if form.is_valid():
            venta = form.save(commit=False)
            venta.user = request.user
            
            # Si es cliente desconocido, asegurarse de que no se asigne cliente
            if form.cleaned_data['tipo_cliente'] == 'minorista':
                venta.cliente = None
            
            # Establecer la fecha actual
            venta.fecha = datetime.now()
                
            venta.save()
            return redirect('detalle_venta', venta_id=venta.id)
    else:
        form = VentaForm(user=request.user)
    
    return render(request, 'venta/venta_form.html', {'form': form, 'titulo': 'Nueva Venta'})

@login_required
@never_cache
def detalle_venta(request, venta_id):
    venta = get_object_or_404(Venta, id=venta_id, user=request.user)
    detalles = venta.detalles.all()
    
    # Initialize forms at the beginning
    form_detalle = DetalleVentaForm()
    form_detalle.fields['producto'].queryset = Producto.objects.filter(user=request.user)
    
    if request.method == 'POST':
        if 'editar_venta' in request.POST:
            form_venta = VentaForm(request.POST, instance=venta, user=request.user)
            if form_venta.is_valid():
                venta_editada = form_venta.save(commit=False)
                
                # Procesar fecha y hora
                try:
                    fecha = request.POST.get('fecha')
                    hora = request.POST.get('hora')
                    if fecha and hora:
                        fecha_hora = datetime.strptime(f"{fecha} {hora}", "%Y-%m-%d %H:%M")
                        venta_editada.fecha = fecha_hora
                    venta_editada.save()
                    messages.success(request, 'Venta actualizada correctamente.')
                except ValueError:
                    messages.error(request, 'Formato de fecha u hora inválido.')
                
                return redirect('detalle_venta', venta_id=venta.id)
        elif 'agregar_detalle' in request.POST:
            form_detalle = DetalleVentaForm(request.POST)
            form_detalle.fields['producto'].queryset = Producto.objects.filter(user=request.user)
            if form_detalle.is_valid():
                detalle = form_detalle.save(commit=False)
                detalle.venta = venta
                if detalle.cantidad > 0:
                    detalle.save()
                else:
                    messages.error(request, 'La cantidad debe ser mayor que 0.')
            else:
                for field, errors in form_detalle.errors.items():
                    for error in errors:
                        messages.error(request, f"{field}: {error}")
            return redirect('detalle_venta', venta_id=venta.id)
    else:
        form_venta = VentaForm(instance=venta, user=request.user)

    context = {
        'venta': venta,
        'detalles': detalles,
        'form_venta': form_venta,
        'form_detalle': form_detalle,
        'titulo': f'Venta #{venta.código}'
    }
    return render(request, 'venta/detalle_venta.html', context)

@login_required
@never_cache
def eliminar_venta(request, venta_id):
    venta = get_object_or_404(Venta, id=venta_id, user=request.user)
    venta.delete()
    return redirect('venta')

@login_required
@never_cache
def eliminar_detalle(request, detalle_id):
    detalle = get_object_or_404(DetalleVenta, id=detalle_id, venta__user=request.user)
    venta_id = detalle.venta.id
    detalle.delete()
    return redirect('detalle_venta', venta_id=venta_id)

@login_required
@never_cache
def descargar_venta_excel(request, venta_id):
    venta = get_object_or_404(Venta, id=venta_id, user=request.user)
    
    # Crear un nuevo libro de trabajo y seleccionar la hoja activa
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = f"Venta #{venta.código}"
    
    # Configurar estilos
    thin_border = Border(left=Side(style='thin'), 
                        right=Side(style='thin'), 
                        top=Side(style='thin'), 
                        bottom=Side(style='thin'))

    table_header_style = NamedStyle(name='table_header_style')
    table_header_style.font = Font(bold=True)
    table_header_style.fill = PatternFill(start_color='4472C4', end_color='4472C4', fill_type='solid')
    table_header_style.alignment = Alignment(horizontal='center', vertical='center')
    table_header_style.border = thin_border

    column_header_style = NamedStyle(name='column_header_style')
    column_header_style.font = Font(bold=True)
    column_header_style.fill = PatternFill(start_color='CCE5FF', end_color='CCE5FF', fill_type='solid')
    column_header_style.alignment = Alignment(horizontal='center', vertical='center')
    column_header_style.border = thin_border

    data_style = NamedStyle(name='data_style')
    data_style.alignment = Alignment(horizontal='left', vertical='center')
    data_style.border = thin_border
    
    # Escribir la información de la venta
    # Título de la primera tabla
    ws.merge_cells('A1:B1')
    ws['A1'] = "Información de la Venta"
    ws['A1'].style = table_header_style
    
    # Encabezados y datos de la primera tabla
    headers = [('A2', 'Código'), ('A3', 'Fecha'), ('A4', 'Cliente'), ('A5', 'Total')]
    for cell_ref, header in headers:
        ws[cell_ref] = header
        ws[cell_ref].style = column_header_style
    
    # Datos
    ws['B2'] = venta.código
    ws['B3'] = venta.fecha.strftime('%d/%m/%Y %H:%M')
    ws['B4'] = venta.cliente.nombre if venta.cliente else "Cliente Desconocido"
    ws['B5'] = f"${venta.total}"
    
    for row in range(2, 6):
        ws[f'B{row}'].style = data_style
    
    # Agregar dos filas en blanco
    current_row = 8
    
    # Título de la segunda tabla
    ws.merge_cells(f'A{current_row}:D{current_row}')
    ws[f'A{current_row}'] = "Detalles de la Venta"
    ws[f'A{current_row}'].style = table_header_style
    
    # Encabezados de la segunda tabla
    current_row += 1
    headers = ['Producto', 'Cantidad', 'Precio Unitario', 'Subtotal']
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=current_row, column=col)
        cell.value = header
        cell.style = column_header_style
    
    # Agregar los detalles de la venta
    current_row += 1
    for detalle in venta.detalles.all():
        nombre_producto = detalle.producto.nombre if detalle.producto else f"{detalle.nombre_producto} (Producto eliminado)"
        ws.cell(row=current_row, column=1, value=nombre_producto).style = data_style
        ws.cell(row=current_row, column=2, value=detalle.cantidad).style = data_style
        ws.cell(row=current_row, column=3, value=f"${detalle.precio_unitario}").style = data_style
        ws.cell(row=current_row, column=4, value=f"${detalle.subtotal}").style = data_style
        current_row += 1
    
    # Ajustar ancho de columnas
    for column in ws.columns:
        max_length = 0
        column_letter = openpyxl.utils.get_column_letter(column[0].column)
        for cell in column:
            try:
                if len(str(cell.value)) > max_length:

templates/venta/venta_form.html
{% extends "layout/base.html" %}

{% load static %}

{% block 'title'%} {{ titulo }} {% endblock %}

{% block 'activo-venta' %}activo{% endblock %}
{% block 'activador-venta' %}activo{% endblock %}

{% block 'content' %}
<div class="container mt-4">

    <div class="container d-flex">
        <a class="morado" href="{% url 'venta' %}" role="button">  
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
        </a>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card sombra borde">
                <div class="card-header">
                    <h4 class="card-title text-center mb-0">{{ titulo }}</h4>
                </div>
                <div class="card-body">
                    <form class="" action="" method="POST">
                        {% csrf_token %}
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    <div {% if message.tags %} class="alert alert-primary alerta text-center" role="alert"{% endif %}>{{ message }}</div>
                                {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="mb-3">
                            <label class="form-label">Tipo de Cliente</label>
                            <div class="d-flex gap-3 align-items-center justify-content-center">
                                {% for radio in form.tipo_cliente %}
                                    <div class="form-check d-flex align-items-center">
                                        {{ radio.tag }}
                                        <label class="form-check-label" for="{{ radio.id_for_label }}">
                                            {{ radio.choice_label }}
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                        <div id="cliente-container" class="mb-3" style="display: none;">
                            <label for="{{ form.cliente.id_for_label }}" class="form-label">Cliente</label>
                            {{ form.cliente }}
                        </div>

                        <div class="mb-3">
                            <label for="{{ form.código.id_for_label }}" class="form-label d-block">Código de Venta</label>
                            <div class="d-flex justify-content-center">
                                {{ form.código }}
                            </div>
                        </div>

                        <div class="text-center">
                            <input class="btn boton mt-3" type="submit" value="Crear Venta">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#id_cliente').select2({
            theme: "bootstrap-5",
            placeholder: "Buscar cliente...",
            width: '100%',
            selectionCssClass: "form-select",
            dropdownCssClass: "form-select"
        });

        // Función para mostrar/ocultar el selector de cliente
        function toggleClienteSelector() {
            if ($('input[name="tipo_cliente"]:checked').val() === 'registrado') {
                $('#cliente-container').show();
                $('#id_cliente').prop('required', true);
            } else {
                $('#cliente-container').hide();
                $('#id_cliente').prop('required', false);
                $('#id_cliente').val('').trigger('change');
            }
        }

        // Ejecutar al cargar la página
        toggleClienteSelector();

        // Ejecutar cuando cambie la selección
        $('input[name="tipo_cliente"]').change(toggleClienteSelector);
    });
</script>

{% endblock %}