ia/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('consejos/', views.consejos, name="consejos"),
]

stock/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('categorias_productos/', views.categorias_productos, name="categorias_productos"),
    path('nueva_categoria/', views.nueva_categoria, name="nueva_categoria"),
    path('eliminar_categoria/<int:id>', views.eliminar_categoria, name="eliminar_categoria"),
    path('productos/stock-bajo-general/', views.productos_con_stock_bajo_general, name='productos_stock_bajo_general'),

    path('lista_productos/<int:id>', views.lista_productos, name="lista_productos"),
    path('nuevo_producto/<int:id>', views.nuevo_producto, name="nuevo_producto"),
    path('producto/<int:id>', views.producto, name="producto"),
    path('editar_producto/<int:id>', views.editar_producto, name="editar_producto"),
    path('eliminar_producto/<int:id>', views.eliminar_producto, name="eliminar_producto"),
    path('productos/stock-bajo/<int:id>', views.productos_con_stock_bajo, name='productos_stock_bajo'),
    path('exportar-productos-excel/', views.exportar_productos_excel, name='exportar_productos_excel'),
    path('exportar-productos-categoria-excel/<int:id>/', views.exportar_productos_categoria_excel, name='exportar_productos_categoria_excel'),
    path('exportar-productos-stock-bajo-excel/', views.exportar_productos_stock_bajo_excel, name='exportar_productos_stock_bajo_excel'),
    path('exportar-productos-stock-bajo-categoria-excel/<int:id>/', views.exportar_productos_stock_bajo_categoria_excel, name='exportar_productos_stock_bajo_categoria_excel'),
]

stock/models.py
from django.db import models
from django.conf import settings
from agenda.models import Proveedor

# Create your models here.
class Categoria(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=False, blank=False)
    descripción = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['user']),  # Índice para mejorar consultas por usuario
            models.Index(fields=['nombre']),  # Índice para búsquedas por nombre
        ]

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    TIPO_STOCK_CHOICES = [
        ("UNIDADES", "Unidades"),
        ("KILOGRAMOS", "Kilogramos"),
        ("LITROS", "Litros"),
        ("PALETS", "Palets"),
        ("METROS CÚBICOS", "Metros cúbicos"),
        ("PROYECTOS", "Proyectos"),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    categoría = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.SET_NULL, null=True, blank=True)
    nombre = models.CharField(max_length=40, null=False, blank=False)
    código = models.IntegerField(null=False, blank=False)
    descripción = models.CharField(max_length=255, blank=True, null=True)
    precio_de_adquisición = models.DecimalField(max_digits=10, verbose_name="Coste de adquisición", decimal_places=2, null=False, blank=False)
    precio_de_venta = models.DecimalField(max_digits=10, verbose_name="Precio de venta", decimal_places=2, null=False, blank=False)
    unidad_de_medida = models.CharField(max_length=20, default="Unidades", choices=TIPO_STOCK_CHOICES, verbose_name="Este producto se vende por")
    stock = models.IntegerField(null=False, blank=False)
    alerta_stock = models.PositiveIntegerField(default=10, verbose_name="Alerta de inventario", help_text="Nivel de stock que activa la alerta")
    fecha_de_creación = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación", null=False, blank=False)

    class Meta:
        indexes = [
            models.Index(fields=['user']),
            models.Index(fields=['categoría']),
            models.Index(fields=['nombre']),
            models.Index(fields=['stock']),
            models.Index(fields=['alerta_stock']),
            models.Index(fields=['código']),
        ]

    def __str__(self):
        return f"{self.nombre} ({self.código})"

stock/forms.py
from django import forms
from django.forms import Textarea
from .models import Categoria, Producto, Proveedor

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'
        exclude = ['user']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control m-2', 'placeholder': 'Nombre de la categoría'}),
            'descripción': Textarea(attrs={'class': 'form-control m-2', 'placeholder': 'Descripción de la categoría'}),
        }

class ProductoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['proveedor'].queryset = Proveedor.objects.filter(user=user)

    class Meta:
        model = Producto
        fields = '__all__'
        exclude = ['user', 'categoría', 'fecha_de_creación']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control m-2', 'placeholder': 'Nombre del producto'}),
            'código': forms.NumberInput(attrs={'class': 'form-control m-2', 'type': 'number', 'placeholder': 'código del producto'}),
            'proveedor': forms.Select(attrs={'class': 'form-select m-5', 'placeholder': 'Proveedor del producto'}),
            'descripción': Textarea(attrs={'class': 'form-control m-2', 'placeholder': 'Descripción del producto'}),
            'precio_de_adquisición': forms.NumberInput(attrs={'class': 'form-control m-2', 'type': 'number', 'placeholder': 'Precio de adquisición'}),
            'precio_de_venta': forms.NumberInput(attrs={'class': 'form-control m-2', 'type': 'number', 'placeholder': 'Precio de venta'}),
            'unidad_de_medida': forms.Select(attrs={'class': 'form-select m-2', 'placeholder': 'unidad de medida'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control m-2', 'type': 'number', 'placeholder': 'En Stock'}),
            'alerta_stock': forms.NumberInput(attrs={'class': 'form-control m-2', 'type': 'number', 'placeholder': 'Alerta para bajo stock'}),
            }  

    def clean(self):
        cleaned_data = super().clean()
        precio_de_adquisición = cleaned_data.get('precio_de_adquisición')
        precio_de_venta = cleaned_data.get('precio_de_venta')
        stock = cleaned_data.get('stock')
        alerta_stock = cleaned_data.get('alerta_stock')
        código = cleaned_data.get('código')
        
        if precio_de_adquisición:
            if precio_de_adquisición <= 0:
                self.add_error('precio_de_adquisición', 'El precio de adquisición es incorrecto.')
        else:
            self.add_error('precio_de_adquisición', 'El precio de adquisición es incorrecto.')

        if código:
            if precio_de_adquisición <= 0:
                self.add_error('código', 'El código es incorrecto.')
        else:
            self.add_error('código', 'El código es incorrecto.')    

        if precio_de_venta:
            if precio_de_venta <= 0:
                self.add_error('precio_de_venta', 'El precio de venta es incorrecto.')
        else:
            self.add_error('precio_de_venta', 'El precio de venta es incorrecto.')

        if stock:
            if stock <= 0:
                self.add_error('stock', 'El valor de este campo es incorrecto.')
        else:
            self.add_error('stock', 'El valor de este campo es incorrecto.')

        if alerta_stock:
            if alerta_stock <= 0:
                self.add_error('alerta_stock', 'El valor de este campo es incorrecto.')
        else:
            self.add_error('alerta_stock', 'El valor de este campo es incorrecto.')
        
        return cleaned_data 

stock/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Categoria, Producto
from .forms import CategoriaForm, ProductoForm
from django.contrib import messages
from django.db.models import Count, F, Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from openpyxl import Workbook
from openpyxl.styles import NamedStyle, Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from django.http import HttpResponse
from django.views.decorators.cache import never_cache

@login_required
@never_cache
def categorias_productos(request):
    categorias_list = Categoria.objects.filter(
        user=request.user, 
        nombre__icontains=request.GET.get('search', '')
    ).annotate(
        productos_bajo_stock=Count(
            'producto',
            filter=Q(producto__stock__lt=F('producto__alerta_stock')),
        )
    ).select_related('user').order_by('nombre')
    productos_bajo_stock = sum(c.productos_bajo_stock for c in categorias_list)
    
    page = request.GET.get('page', 1)
    paginator = Paginator(categorias_list, 20)
    try:
        categorias = paginator.page(page)
    except PageNotAnInteger:
        categorias = paginator.page(1)
    except EmptyPage:
        categorias = paginator.page(paginator.num_pages)
    context = {
        'categorias': categorias,
        'productos_bajo_stock': productos_bajo_stock,
        'total': categorias_list.count()
    }
    return render(request, 'stock/categorías.html', context)

@login_required
@never_cache
def eliminar_categoria(request, id):
    categoria = get_object_or_404(Categoria.objects.select_related('user'), id=id, user=request.user)
    categoria.delete()
    return redirect ('categorias_productos')

@login_required
@never_cache
def nueva_categoria(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            categoria = form.save(commit=False)
            categoria.user = request.user
            categoria.save()
            return redirect('categorias_productos')
        else:
            messages.error(request, "Alguno de los datos introducidos no son válidos, revise nuevamente cada campo")
    else:
        form = CategoriaForm()
    context = {'form': form}
    return render(request, 'stock/nueva_categoria.html', context)

#--------------------------------------------------------------------------------------------------

@login_required
@never_cache
def lista_productos(request, id):
    categoria = get_object_or_404(Categoria.objects.select_related('user'), user=request.user, id=id)
    form = CategoriaForm(instance=categoria)
    productos_list = Producto.objects.filter(
        Q(user=request.user),
        Q(categoría=id),
        Q(nombre__icontains=request.GET.get('search', '')) | Q(código__icontains=request.GET.get('search', ''))
    ).select_related('user').order_by('nombre')
    
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            return redirect('lista_productos', id=categoria.id)
        else:
            return redirect(request.META.get('HTTP_REFERER', 'lista_productos'))
    alertas = [
        {
            'existencia': existencia,
            'existencia_fisica': existencia.stock,
        }
        for existencia in productos_list if existencia.stock <= existencia.alerta_stock
    ]

    page = request.GET.get('page', 1)
    paginator = Paginator(productos_list, 20)
    try:
        productos = paginator.page(page)
    except PageNotAnInteger:
        productos = paginator.page(1)
    except EmptyPage:
        productos = paginator.page(paginator.num_pages)

    context = {
        'productos': productos,
        'total': productos_list.count(),
        'categoria': categoria,
        'form': form,
        'total_alertas': len(alertas),
    }
    return render(request, "stock/productos.html", context)


@login_required
@never_cache
def nuevo_producto(request, id):
    categoria = get_object_or_404(Categoria.objects.select_related('user'), user=request.user, id=id)
    if request.method == 'POST':
        form = ProductoForm(request.POST, user=request.user)
        if form.is_valid():
            producto = form.save(commit=False)
            producto.user = request.user
            producto.categoría = categoria
            producto.save()
            return redirect('producto', id=producto.id)
        else:
            messages.error(request, "Alguno de los datos introducidos no son válidos, revise nuevamente cada campo")
    else:
        form = ProductoForm(user=request.user)
    context = {
        'form': form,
        'categoria': categoria,
    }
    return render(request, 'stock/nuevo_producto.html', context)

#-------------------------------------------------------------------------------------          

@login_required 
@never_cache
def producto(request, id):
    producto = get_object_or_404(Producto.objects.select_related('user'), id=id, user=request.user)
    context = {
        'producto': producto
    }
    return render(request, 'stock/producto.html', context)

@login_required
@never_cache
def eliminar_producto(request, id):
    producto = get_object_or_404(Producto.objects.select_related('user'), id=id, user=request.user)
    producto.delete()
    return redirect('lista_productos', id=producto.categoría.id)

@login_required
@never_cache
def productos_con_stock_bajo_general(request):
    productos_bajo_stock_list = Producto.objects.filter(user=request.user, stock__lt=F('alerta_stock')).select_related('user').order_by('nombre')
    page = request.GET.get('page', 1)
    paginator = Paginator(productos_bajo_stock_list, 20)
    try:
        productos_bajo_stock = paginator.page(page)
    except PageNotAnInteger:
        productos_bajo_stock = paginator.page(1)
    except EmptyPage:
        productos_bajo_stock = paginator.page(paginator.num_pages) 
    context = {
        'productos': productos_bajo_stock,
    }
    return render(request, 'stock/stock_bajo.html', context)

@login_required
@never_cache
def productos_con_stock_bajo(request, id):
    productos_bajo_stock_list = Producto.objects.filter(user=request.user, categoría=id, stock__lt=F('alerta_stock')).select_related('user').order_by('nombre')
    categoria = categoria = get_object_or_404(Categoria.objects.select_related('user'), id=id, user=request.user)
    page = request.GET.get('page', 1)
    paginator = Paginator(productos_bajo_stock_list, 20)
    try:
        productos_bajo_stock = paginator.page(page)
    except PageNotAnInteger:
        productos_bajo_stock = paginator.page(1)
    except EmptyPage:
        productos_bajo_stock = paginator.page(paginator.num_pages)
    context = {
        'productos': productos_bajo_stock,
        'categoria': categoria
    }
    return render(request, 'stock/productos_stock_bajo.html', context)

@login_required
@never_cache
def editar_producto(request, id):
    producto = get_object_or_404(Producto.objects.select_related('user'), id=id, user=request.user)
    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('producto', id=id)
        else:
            messages.error(request, "Alguno de los datos introducidos no son válidos, revise nuevamente cada campo")
    else:
        form = ProductoForm(instance=producto, user=request.user)
    context = {
        'form': form,
        'producto': producto,
    }
    return render(request, 'stock/editar_producto.html', context)

def get_proveedor_nombre(proveedor):
    return proveedor.nombre if proveedor else "Eliminado"

@login_required
@never_cache
def exportar_productos_excel(request):
    # Obtener todos los productos del usuario
    productos = Producto.objects.filter(user=request.user).select_related('categoría', 'proveedor')
    
    # Crear un nuevo libro de Excel
    wb = Workbook()
    ws = wb.active
    ws.title = "Categorías"
    
    # Definir estilos
    header_style = NamedStyle(name='header_style')
    header_style.font = Font(bold=True, color='FFFFFF')
    header_style.fill = PatternFill(start_color='0D6EFD', end_color='0D6EFD', fill_type='solid')
    header_style.alignment = Alignment(horizontal='left', vertical='center')
    header_style.border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )

    # Estilo para las celdas de datos
    data_style = NamedStyle(name='data_style')
    data_style.alignment = Alignment(horizontal='left', vertical='center')
    data_style.border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Definir encabezados
    headers = [
        'Código',
        'Nombre',
        'Categoría',
        'Proveedor',
        'Descripción',
        'Precio de Adquisición',
        'Precio de Venta',
        'Unidad de Medida',
        'Stock Actual',
        'Alerta de Stock'
    ]
    
    # Escribir encabezados
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.style = header_style
        ws.column_dimensions[get_column_letter(col)].width = 15
    
    # Escribir datos
    for row, producto in enumerate(productos, 2):
        cells = [
            (producto.código),
            (producto.nombre),
            (producto.categoría.nombre),
            (get_proveedor_nombre(producto.proveedor)),
            (producto.descripción or ""),
            (float(producto.precio_de_adquisición)),
            (float(producto.precio_de_venta)),
            (producto.unidad_de_medida),
            (producto.stock),

templates/stock/editar_producto.html
{% extends "layout/base.html" %}

{% block 'title'%} Editar Producto {% endblock %}

{% block 'activo-stock' %}activo{% endblock %}
{% block 'activador-stock' %}activo{% endblock %}

{% block 'styles' %}
{% load static %}
<link rel="stylesheet" href="{% static "css/forms.css" %}">
{% endblock %}

{% block 'content' %}
<div class="container mt-4">

    <div class="container d-flex">
        <a class="morado" href="{% url "producto" id=producto.id %}" role="button">  
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
        </a>
    </div>

    <h1 class="text-center">Editar Producto {{ producto.nombre }}</h1>
    <div class="d-flex justify-content-center align-items-center">
    <form  class=" p-5 rounded-3 sombra borde bg-body-tertiary" actions="" method="POST">
      {% csrf_token %}
      {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-primary alerta text-center" role="alert"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
      {% endif %}
        <table>
            {{ form }}
        </table>    
        <input class="btn boton mt-3" type="submit" value="Enviar">
    </form>
    </div>

</div>

<script>
    $(document).ready(function() {
        $('#id_proveedor').select2({
            theme: "bootstrap-5",
            placeholder: "Buscar proveedor...",
            width: '100%',
            selectionCssClass: "form-select",
            dropdownCssClass: "form-select"
        });
    });
</script>

{% endblock %}

templates/stock/nueva_categoria.html
{% extends "layout/base.html" %}

{% block 'title'%} Nueva Categoría {% endblock %}

{% block 'activo-stock' %}activo{% endblock %}
{% block 'activador-stock' %}activo{% endblock %}

{% block 'styles' %}
{% load static %}
<link rel="stylesheet" href="{% static "css/forms.css" %}">
{% endblock %}

{% block 'content' %}
<div class="container mt-4">

    <div class="container d-flex">
        <a class="morado" href="{% url "categorias_productos" %}" role="button">  
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
        </a>
    </div>

    <h1 class="text-center">Nueva Categoría</h1>
    <div class="d-flex justify-content-center align-items-center">
    <form  class=" p-5 rounded-3 sombra borde bg-body-tertiary" actions="" method="POST">
      {% csrf_token %}
      {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-primary alerta text-center" role="alert"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
      {% endif %}
        <table>
            {{ form }}
        </table>    
        <input class="btn boton mt-3" type="submit" value="Enviar">
    </form>
    </div>

</div>
{% endblock %}

templates/stock/nuevo_producto.html
{% extends "layout/base.html" %}

{% block 'title'%} Nuevo Producto {% endblock %}

{% block 'activo-stock' %}activo{% endblock %}
{% block 'activador-stock' %}activo{% endblock %}

{% block 'styles' %}
{% load static %}
<link rel="stylesheet" href="{% static "css/forms.css" %}">
{% endblock %}

{% block 'content' %}
<div class="container mt-4">

    <div class="container d-flex">
        <a class="morado" href="{% url "lista_productos" id=categoria.id %}" role="button">  
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
        </a>
    </div>

    <h1 class="text-center">Nuevo Producto para {{ categoria.nombre }}</h1>
    <div class="d-flex justify-content-center align-items-center">
    <form  class=" p-5 rounded-3 sombra borde bg-body-tertiary" actions="" method="POST">
      {% csrf_token %}
      {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-primary alerta text-center" role="alert"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
      {% endif %}
        <table>
            {{ form }}
        </table>    
        <input class="btn boton mt-3" type="submit" value="Enviar">
    </form>
    </div>

</div>

<script>
    $(document).ready(function() {
        $('#id_proveedor').select2({
            theme: "bootstrap-5",
            placeholder: "Buscar proveedor...",
            width: '100%',
            selectionCssClass: "form-select",
            dropdownCssClass: "form-select"
        });
    });
</script>

{% endblock %}

templates/stock/producto.html
{% extends "layout/base.html" %}

{% load static %}

{% block 'title'%} Producto {% endblock %}

{% block 'activo-stock' %}activo{% endblock %}
{% block 'activador-stock' %}activo{% endblock %}

{% block 'content' %}
<div class="container mt-4">

    <div class="container d-flex">
        <a class="morado" href="{% url "lista_productos" id=producto.categoría.id %}" role="button">  
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
        </a>
    </div>

    <h1 class="text-center">{{ producto.nombre }}</h1>
    <div class="d-flex justify-content-center align-items-center">
        <div class=" p-4 rounded-3 sombra borde bg-body-tertiary">
            <img class="d-block mx-auto my-2" src="{% static "images/product-plus.png" %}">
            <p class="m-1"><b>Nombre:</b> {{ producto.nombre }}</p>
            <p class="m-1"><b>Código:</b> {{ producto.código }}</p>
            <p class="m-1"><b>Categoría:</b> {{ producto.categoría }}</p>
            <p class="m-1"><b>Proveedor:</b>
                {% if producto.proveedor == None %}
                    <span class="text-danger">Eliminado</span>
                {% else %}
                    {{ producto.proveedor }}
                {% endif %}
            </p>
            <p class="m-1"><b>Descripción:</b> 
                {% if producto.descripción == None %}
                    Sin descripción
                {% else %}
                    {{ producto.descripción }}
                {% endif %}
            </p>
            <p class="m-1"><b>Precio de adquisición:</b> {{ producto.precio_de_adquisición }}</p>
            <p class="m-1"><b>Precio de venta:</b> {{ producto.precio_de_venta }}</p>
            <p class="m-1"><b>Unidad de medida:</b> {{ producto.unidad_de_medida }}</p>
            <p class="m-1"><b>Stock:</b> {{ producto.stock }}</p>
            <p class="m-1"><b>Alerta stock bajo:</b> {{ producto.alerta_stock }}</p>
            <a class="btn boton btn-sm m-1" href="{% url "editar_producto" id=producto.id %}" role="button">
                Editar
                <img class="" src="{% static "images/pages.png" %}">
            </a>
            <button type="button" class="btn btn-danger rounded-pill btn-sm m-1" data-bs-toggle="modal" data-bs-target="#modal-eliminar">
                Eliminar 
                <img class="" src="{% static "images/trash.png" %}">
            </button>
            <div class="modal fade" id="modal-eliminar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Atención</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Esta seguro de <b>eliminar</b> el producto <b>{{ producto.nombre }}</b>
                        <p class="mt-2"><b>Si elimina este producto tambien se eliminaran su historial de ventas</b></p>
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-danger rounded-pill" href="{% url "eliminar_producto" id=producto.id %}">Estoy seguro</a>
                        <button type="button" class="btn boton" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}